# Harmono Jekyll theme general configurations

# Site URL
# url: https://kuoe0.github.io
url: "https://blog.kuoe0.tw"
enforce_ssl: "blog.kuoe0.tw"
# Base URL (https://kuoe0.github.io{/baseurl})
baseurl: ""

# Site Title
title: KuoE0's Dots
# Little description about your site
description: Connect the dots in the future.

# Harmono theme configuration. Please change accordingly.
harmono:
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-26646299-1
  # Profile links, leave blank to ignore
  social:
    email:    kuoe0.tw@gmail.com
    linkedin: kuoe0
    github:   kuoe0

  page_list:
    - About
    - Archive

  # Toggle disclaimer in footer
  show_disclaimer: true

  # Toggle comment system
  comment: true
  # Comment system provider
  disqus:
    short_name: kuoe0sdots

# Conversion / Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# source code highlight
highlighter: rouge # must be rouge if using Jekyll 3.0+

# Permalinks
permalink: "/posts/:year/:month/:day/:title/"

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed

feed:
  path: atom.xml

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
